server:
  port: 9999
spring:
  application:
    name: mock-webflux-server
  jackson:
    default-property-inclusion: non_null
  cache:
    type: caffeine
    cache-names:
      - web-content
      - fixture-data
      - httpbin-image
management:
  endpoints:
    web:
      exposure:
        include: health,info
logging:
  level:
    io.bluetape4k.mockwebflux: INFO
