package io.bluetape4k.exposed.trino

import java.sql.Connection
import java.sql.PreparedStatement

/**
 * Trino JDBC Connection 래퍼.
 *
 * Trino JDBC 드라이버는 다음 오버로드를 지원하지 않습니다:
 * - `prepareStatement(sql, autoGeneratedKeys)`
 * - `prepareStatement(sql, columnIndexes)`
 * - `prepareStatement(sql, columnNames)`
 *
 * 위 메서드들을 `prepareStatement(sql)` 로 위임하여 Exposed ORM과의 호환성을 보장합니다.
 *
 * **주의사항:**
 * - Trino는 트랜잭션을 지원하지 않습니다. autocommit 모드로 실행됩니다.
 * - 원자성(Atomicity) 보장 없음 — 블록 중간 실패 시 앞선 DML은 롤백되지 않습니다.
 * - [rollback] no-op — Exposed 프레임워크 인터페이스 호환을 위한 어댑터입니다.
 * - Nested transaction / Savepoint 미지원 — 호출은 허용되나 원자성 없습니다.
 * - Multi-statement 쓰기 블록 사용 시 부분 반영 위험을 인지해야 합니다.
 */
@Suppress("JavaDefaultMethodsNotOverriddenByDelegation")
internal class TrinoConnectionWrapper(private val conn: Connection): Connection by conn {

    init {
        // Exposed가 조회하는 상태값과 실제 JDBC 연결 상태를 맞춰 둡니다.
        conn.autoCommit = true
    }

    /**
     * Trino는 항상 autocommit 모드로 동작하므로, 항상 `true`를 반환합니다.
     */
    override fun getAutoCommit(): Boolean = true

    /**
     * Trino는 autocommit 모드만 지원하므로, 설정을 무시합니다 (no-op).
     */
    override fun setAutoCommit(autoCommit: Boolean) {
        // Trino는 autocommit=true만 지원. 이미 true가 아닐 때만 설정합니다.
        if (!conn.autoCommit) conn.autoCommit = true
    }

    /**
     * Trino는 트랜잭션을 지원하지 않으므로, commit은 no-op입니다.
     * Exposed 프레임워크 호환을 위한 어댑터입니다.
     */
    override fun commit() {
        // no-op: Trino는 트랜잭션을 지원하지 않음
    }

    /**
     * Trino는 트랜잭션을 지원하지 않으므로, rollback은 no-op입니다.
     * Exposed 프레임워크 호환을 위한 어댑터입니다.
     */
    override fun rollback() {
        // no-op: Trino는 트랜잭션을 지원하지 않음
    }

    override fun prepareStatement(sql: String, autoGeneratedKeys: Int): PreparedStatement =
        conn.prepareStatement(sql)

    override fun prepareStatement(sql: String, columnIndexes: IntArray): PreparedStatement =
        conn.prepareStatement(sql)

    override fun prepareStatement(sql: String, columnNames: Array<out String>): PreparedStatement =
        conn.prepareStatement(sql)
}
