package io.bluetape4k.jdbc.sql

import io.bluetape4k.assertions.shouldBeEqualTo
import io.bluetape4k.assertions.shouldBeGreaterThan
import io.bluetape4k.assertions.shouldNotBeNull
import org.junit.jupiter.api.Test
import java.sql.Statement

/**
 * [ConnectionExtensions] 확장 함수 테스트.
 *
 * [Connection.executeUpdateWithIndedexes], [Connection.executeUpdateWithLabels],
 * [Connection.executeBatch] (vararg) 등 기존 테스트에서 누락된 공개 API를 검증합니다.
 */
class ConnectionExtensionsTest : AbstractJdbcSqlTest() {

    // ─── executeUpdateWithIndedexes ────────────────────────────────────────────

    @Test
    fun `executeUpdateWithIndedexes - 컬럼 인덱스로 생성된 키 반환`() {
        dataSource.withConnect { conn ->
            val affected = conn.executeUpdateWithIndedexes(
                "INSERT INTO Actors (firstname, lastname) VALUES ('IndexKey', 'Test')",
                1  // 첫 번째 컬럼(id)의 생성된 키
            )

            affected shouldBeEqualTo 1
        }

        val count = dataSource.runQuery(
            "SELECT COUNT(*) FROM Actors WHERE firstname = 'IndexKey'"
        ) { rs -> rs.next(); rs.getInt(1) }
        count shouldBeEqualTo 1
    }

    @Test
    fun `executeUpdateWithIndedexes - 다중 컬럼 인덱스`() {
        dataSource.withConnect { conn ->
            val affected = conn.executeUpdateWithIndedexes(
                "INSERT INTO Actors (firstname, lastname) VALUES ('MultiIndex', 'Test')",
                1
            )
            affected shouldBeEqualTo 1
        }
    }

    // ─── executeUpdateWithLabels ───────────────────────────────────────────────

    @Test
    fun `executeUpdateWithLabels - 컬럼 레이블로 INSERT 실행`() {
        dataSource.withConnect { conn ->
            val affected = conn.executeUpdateWithLabels(
                "INSERT INTO Actors (firstname, lastname) VALUES ('LabelKey', 'Test')",
                "id"
            )

            affected shouldBeEqualTo 1
        }

        val count = dataSource.runQuery(
            "SELECT COUNT(*) FROM Actors WHERE firstname = 'LabelKey'"
        ) { rs -> rs.next(); rs.getInt(1) }
        count shouldBeEqualTo 1
    }

    // ─── executeBatch (vararg SQL) ────────────────────────────────────────────

    @Test
    fun `executeBatch vararg - 여러 SQL 문을 배치 실행`() {
        dataSource.withConnect { conn ->
            val results = conn.executeBatch(
                "INSERT INTO Actors (firstname, lastname) VALUES ('Batch1', 'VarargTest')",
                "INSERT INTO Actors (firstname, lastname) VALUES ('Batch2', 'VarargTest')",
                "INSERT INTO Actors (firstname, lastname) VALUES ('Batch3', 'VarargTest')"
            )

            results.size shouldBeEqualTo 3
        }

        val count = dataSource.runQuery(
            "SELECT COUNT(*) FROM Actors WHERE lastname = 'VarargTest'"
        ) { rs -> rs.next(); rs.getInt(1) }
        count shouldBeEqualTo 3
    }

    @Test
    fun `executeBatch vararg - 단일 SQL 배치 실행`() {
        dataSource.withConnect { conn ->
            val results = conn.executeBatch(
                "INSERT INTO Actors (firstname, lastname) VALUES ('SingleBatch', 'VarargSingle')"
            )
            results.size shouldBeEqualTo 1
        }
    }

    // ─── preparedStatement with autoGeneratedKeys ─────────────────────────────

    @Test
    fun `preparedStatement with autoGeneratedKeys - 생성된 키 반환`() {
        val generatedId = dataSource.withConnect { conn ->
            conn.preparedStatement(
                "INSERT INTO Actors (firstname, lastname) VALUES (?, ?)",
                Statement.RETURN_GENERATED_KEYS
            ) { stmt ->
                stmt.setString(1, "GeneratedPS")
                stmt.setString(2, "Test")
                stmt.executeUpdate()
                stmt.generatedKeys.use { rs ->
                    if (rs.next()) rs.getLong(1) else null
                }
            }
        }

        generatedId.shouldNotBeNull()
        generatedId shouldBeGreaterThan 0L
    }

    // ─── preparedStatement with columnIndexes ─────────────────────────────────

    @Test
    fun `preparedStatement with columnIndexes - 컬럼 인덱스 기반 생성키 반환`() {
        val generatedId = dataSource.withConnect { conn ->
            conn.preparedStatement(
                "INSERT INTO Actors (firstname, lastname) VALUES (?, ?)",
                intArrayOf(1)
            ) { stmt ->
                stmt.setString(1, "ColIndexPS")
                stmt.setString(2, "Test")
                stmt.executeUpdate()
                stmt.generatedKeys.use { rs ->
                    if (rs.next()) rs.getLong(1) else null
                }
            }
        }

        generatedId.shouldNotBeNull()
        generatedId shouldBeGreaterThan 0L
    }

    // ─── preparedStatement with columnNames ───────────────────────────────────

    @Test
    fun `preparedStatement with columnNames - 컬럼 이름 기반 생성키 반환`() {
        val generatedId = dataSource.withConnect { conn ->
            conn.preparedStatement(
                "INSERT INTO Actors (firstname, lastname) VALUES (?, ?)",
                arrayOf("id")
            ) { stmt ->
                stmt.setString(1, "ColNamePS")
                stmt.setString(2, "Test")
                stmt.executeUpdate()
                stmt.generatedKeys.use { rs ->
                    if (rs.next()) rs.getLong(1) else null
                }
            }
        }

        generatedId.shouldNotBeNull()
        generatedId shouldBeGreaterThan 0L
    }

    // ─── executeInsert ────────────────────────────────────────────────────────

    @Test
    fun `Connection executeInsert - INSERT 후 생성된 키 반환`() {
        val generatedId = dataSource.withConnect { conn ->
            conn.executeInsert(
                "INSERT INTO Actors (firstname, lastname) VALUES ('ExecInsert', 'Test')"
            ) { rs ->
                if (rs.next()) rs.getLong(1) else null
            }
        }

        generatedId.shouldNotBeNull()
        generatedId shouldBeGreaterThan 0L
    }

    // ─── DataSource executeUpdateWithIndedexes / executeUpdateWithLabels ───────

    @Test
    fun `DataSource executeUpdateWithIndedexes - 컬럼 인덱스로 INSERT 실행`() {
        val affected = dataSource.executeUpdateWithIndedexes(
            "INSERT INTO Actors (firstname, lastname) VALUES ('DSIndexKey', 'Test')",
            1
        )
        affected shouldBeEqualTo 1
    }

    @Test
    fun `DataSource executeUpdateWithLabels - 컬럼 레이블로 INSERT 실행`() {
        val affected = dataSource.executeUpdateWithLabels(
            "INSERT INTO Actors (firstname, lastname) VALUES ('DSLabelKey', 'Test')",
            "id"
        )
        affected shouldBeEqualTo 1
    }

    @Test
    fun `Connection executeUpdate with autoGeneratedKeys - 생성 키 옵션을 전달한다`() {
        val affected = dataSource.withConnect { conn ->
            conn.executeUpdate(
                "INSERT INTO Actors (firstname, lastname) VALUES ('ConnectionKeys', 'Test')",
                Statement.RETURN_GENERATED_KEYS
            )
        }

        affected shouldBeEqualTo 1
    }

    @Test
    fun `DataSource executeUpdate with autoGeneratedKeys - 생성 키 옵션을 전달한다`() {
        val affected = dataSource.executeUpdate(
            "INSERT INTO Actors (firstname, lastname) VALUES ('DataSourceKeys', 'Test')",
            Statement.RETURN_GENERATED_KEYS
        )

        affected shouldBeEqualTo 1
    }

    @Test
    fun `DataSource executeInsert - 생성된 키를 매핑한다`() {
        val generatedId = dataSource.executeInsert(
            "INSERT INTO Actors (firstname, lastname) VALUES ('DataSourceInsert', 'Test')"
        ) { rs ->
            if (rs.next()) rs.getLong(1) else null
        }

        generatedId.shouldNotBeNull()
        generatedId shouldBeGreaterThan 0L
    }

    @Test
    fun `DataSource executeBatch - 여러 SQL 문을 배치 실행한다`() {
        val results = dataSource.executeBatch(
            "INSERT INTO Actors (firstname, lastname) VALUES ('DataSourceBatch1', 'Test')",
            "INSERT INTO Actors (firstname, lastname) VALUES ('DataSourceBatch2', 'Test')"
        )

        results.size shouldBeEqualTo 2
    }
}
