spring:
    data:
        redis:
            repositories:
                enabled: true

            host: ${testcontainers.redis.host}
            port: ${testcontainers.redis.port}

            lettuce:
                pool:
                    enabled: true
                    max-active: 32
                    max-idle: 8
                    min-idle: 2
