package io.bluetape4k.exposed.clickhouse

import io.mockk.every
import io.mockk.mockk
import io.mockk.verify
import org.amshove.kluent.shouldBeEqualTo
import org.junit.jupiter.api.BeforeEach
import org.junit.jupiter.api.Test
import java.sql.Connection
import java.sql.PreparedStatement
import java.sql.Statement

/**
 * [ClickHouseConnectionWrapper] 단위 테스트.
 *
 * MockK로 [Connection] 모의 객체를 만들어, autocommit/commit/rollback/prepareStatement
 * 동작이 명세대로 동작하는지 확인합니다.
 */
class ClickHouseConnectionWrapperTest {

    private lateinit var mockConn: Connection

    @BeforeEach
    fun setup() {
        mockConn = mockk(relaxed = true)
        every { mockConn.autoCommit } returns true
    }

    @Test
    fun `autoCommit is always true`() {
        val wrapper = ClickHouseConnectionWrapper(mockConn)
        wrapper.autoCommit shouldBeEqualTo true
    }

    @Test
    fun `setAutoCommit false is ignored`() {
        val wrapper = ClickHouseConnectionWrapper(mockConn)
        wrapper.setAutoCommit(false)
        wrapper.autoCommit shouldBeEqualTo true
    }

    @Test
    fun `commit is no-op`() {
        val wrapper = ClickHouseConnectionWrapper(mockConn)
        // 예외 없이 반환되어야 합니다.
        wrapper.commit()
    }

    @Test
    fun `rollback is no-op`() {
        val wrapper = ClickHouseConnectionWrapper(mockConn)
        // 예외 없이 반환되어야 합니다.
        wrapper.rollback()
    }

    @Test
    fun `prepareStatement with autoGeneratedKeys delegates to single-arg`() {
        val mockStmt = mockk<PreparedStatement>()
        every { mockConn.prepareStatement(any<String>()) } returns mockStmt

        val wrapper = ClickHouseConnectionWrapper(mockConn)
        val result = wrapper.prepareStatement("SELECT 1", Statement.RETURN_GENERATED_KEYS)

        result shouldBeEqualTo mockStmt
        verify(exactly = 1) { mockConn.prepareStatement("SELECT 1") }
    }

    @Test
    fun `prepareStatement with columnIndexes delegates to single-arg`() {
        val mockStmt = mockk<PreparedStatement>()
        every { mockConn.prepareStatement(any<String>()) } returns mockStmt

        val wrapper = ClickHouseConnectionWrapper(mockConn)
        val result = wrapper.prepareStatement("SELECT 1", intArrayOf(1, 2))

        result shouldBeEqualTo mockStmt
        verify(exactly = 1) { mockConn.prepareStatement("SELECT 1") }
    }

    @Test
    fun `prepareStatement with columnNames delegates to single-arg`() {
        val mockStmt = mockk<PreparedStatement>()
        every { mockConn.prepareStatement(any<String>()) } returns mockStmt

        val wrapper = ClickHouseConnectionWrapper(mockConn)
        val result = wrapper.prepareStatement("SELECT 1", arrayOf("id"))

        result shouldBeEqualTo mockStmt
        verify(exactly = 1) { mockConn.prepareStatement("SELECT 1") }
    }
}
