package io.bluetape4k.exposed.duckdb

import java.sql.Connection
import java.sql.PreparedStatement

/**
 * DuckDB JDBC 1.1.3 호환 Connection 래퍼.
 *
 * DuckDB JDBC 1.1.3은 다음 오버로드를 지원하지 않습니다:
 * - `prepareStatement(sql, autoGeneratedKeys)`
 * - `prepareStatement(sql, columnIndexes)`
 * - `prepareStatement(sql, columnNames)`
 *
 * 위 메서드들을 `prepareStatement(sql)` 로 위임하여 Exposed ORM과의 호환성을 보장합니다.
 * 이 래퍼는 generated key 관련 JDBC 호환성만 보정하며,
 * DuckDB의 트랜잭션 의미론이나 autocommit 동작은 변경하지 않습니다.
 */
@Suppress("JavaDefaultMethodsNotOverriddenByDelegation")
internal class DuckDBConnectionWrapper(private val conn: Connection): Connection by conn {

    override fun prepareStatement(sql: String, autoGeneratedKeys: Int): PreparedStatement =
        conn.prepareStatement(sql)

    override fun prepareStatement(sql: String, columnIndexes: IntArray): PreparedStatement =
        conn.prepareStatement(sql)

    override fun prepareStatement(sql: String, columnNames: Array<out String>): PreparedStatement =
        conn.prepareStatement(sql)
}
